# Generated by Django 3.0.1 on 2019-12-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_auto_20191222_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maths', to='maths.Category'),
        ),
    ]
